FROM node:21.7.3-alpine as aredn-manager-frontend

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

COPY frontend/. .

ENV NODE_ENV=production

RUN npm run build

FROM nginx:1.27.0-alpine

COPY --from=aredn-manager-frontend /app/dist /usr/share/nginx/html
