#!/bin/sh

cleanup() {
  echo "Stopping meshlink..."
  if [ -f /var/run/meshlink.pid ]; then
    kill $(cat /var/run/meshlink.pid) || true
    rm -f /var/run/meshlink.pid
    exit 0
  fi
}
trap cleanup EXIT INT TERM

isolation=""
if [ "$SUPERNODE" = "true" ]; then
  isolation="isolate br-dtdlink"
fi

meshlink \
  -C "upload hosts /etc/meshlink/hosts" \
  -C "upload services /etc/meshlink/services" \
  -C "upload publish /etc/meshlink/publish" \
  -C "upload subscribe /etc/meshlink/subscribe" \
  -C "signal hosts mesh-manager notify-babel" \
  -C "signal services mesh-manager notify-babel" \
  -C "${isolation}" &
pid=$!
echo -n "$pid" > /var/run/meshlink.pid
wait $pid
ret=$?
if [ $ret -ne 0 ]; then
  echo "meshlink exited with code $ret"
  exit $ret
fi
