#!/bin/sh

cleanup() {
  echo "Stopping arednlink..."
  if [ -f /var/run/arednlink.pid ]; then
    kill $(cat /var/run/arednlink.pid) || true
    rm -f /var/run/arednlink.pid
    exit 0
  fi
}
trap cleanup EXIT INT TERM

isolation=""
if [ "$SUPERNODE" = "true" ]; then
  isolation="isolate br-dtdlink"
fi

arednlink \
  -C "upload hosts /etc/arednlink/hosts" \
  -C "upload services /etc/arednlink/services" \
  -C "upload publish /etc/arednlink/publish" \
  -C "upload subscribe /etc/arednlink/subscribe" \
  -C "signal hosts mesh-manager notify-babel" \
  -C "signal services mesh-manager notify-babel" \
  -C "${isolation}" &
pid=$!
echo -n "$pid" > /var/run/arednlink.pid
wait $pid
ret=$?
if [ $ret -ne 0 ]; then
  echo "arednlink exited with code $ret"
  exit $ret
fi
