name: Go Static Checks
on: pull_request

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: |
          cd frontend
          npm ci --ignore-scripts
          npm run build
          cd -

      - uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist
          if-no-files-found: error
          retention-days: 1

  new-frontend:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: |
          cd new-frontend
          npm ci --ignore-scripts
          npm run build
          cd -

      - uses: actions/upload-artifact@v4
        with:
          name: new-frontend
          path: new-frontend/dist
          if-no-files-found: error
          retention-days: 1

  golangci:
    name: lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          skip-cache: true
          # Show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
