name: Per-architecture test

on:
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: cd frontend && npm ci --ignore-scripts
      - run: cd frontend && npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/dist
          if-no-files-found: error
          retention-days: 1

  test-linux:
    name: Test Linux
    runs-on: ubuntu-24.04
    needs: frontend
    strategy:
      fail-fast: false
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Copy built frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/dist

      - run: go generate ./...

      - uses: Wandalen/wretry.action@master
        with:
          command: CGO_ENABLED=0 go test -p 2 -v ./...
          attempt_limit: 3
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: "0"
